### ISSUE TITLE
Case Sensitivity Disparity

### ISSUE THREAD

**Issue by digisavvy** [paulund/wordpress-theme-customizer-custom-controls#7]
Hey there,
Cool project! =)

I Noticed a couple minor items with this project. The issue is that the folder '/WordPress-Theme-Customizer-Custom-Controls' has uppercase characters and the calls to that directory, from within the project, are all lowercase. I noticed this in the layout picker control and also in the google font select document. So just change the folder to lowercase and that'll do the trick

**Comment by paulund** [comment]
Thanks I've changed the projects name now so that should solve this issue.

**Comment by digisavvy** [comment]
Thanks so much
